# Generated by Django 3.1.3 on 2020-11-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefury_backend', '0002_auto_20201107_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='referer_username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
