# Generated by Django 3.1.3 on 2020-11-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefury_backend', '0003_employee_referer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
