# Generated by Django 3.1.3 on 2020-11-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefury_backend', '0004_company_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
